basePath: /api
definitions:
  main.Sample:
    properties:
      id:
        type: integer
      login:
        type: string
      lorem:
        type: string
    type: object
  request.LoginRequest:
    properties:
      isRemember:
        type: boolean
      login:
        type: string
      password:
        type: string
    required:
    - isRemember
    - login
    - password
    type: object
  response.LoginInfo:
    properties:
      token:
        type: string
      username:
        type: string
    required:
    - token
    - username
    type: object
  response.Parameter:
    properties:
      defaultValue:
        type: string
      id:
        type: integer
      isDefault:
        type: boolean
      isSystem:
        type: boolean
      name:
        type: string
      parameterType:
        type: string
    required:
    - defaultValue
    - id
    - isDefault
    - isSystem
    - name
    - parameterType
    type: object
host: localhost:8080
info:
  contact: {}
  description: CMS с сервером на языке программирования GO
  title: keeper cms server
  version: "0.1"
paths:
  /auth/change-password:
    post:
      description: Меняет пароль по запросу пользователя
      parameters:
      - description: Параметры смены пароля
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginInfo'
      summary: Меняет пароль для пользователя
      tags:
      - auth
  /auth/login:
    post:
      description: Проводит авторизацию на сервере и возвращает информацию о пользователе.
      parameters:
      - description: Параметры аунтификации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginInfo'
      summary: Авторизирует пользователя.
      tags:
      - auth
  /parameter:
    get:
      description: Возвращает массив параметров, предназначеных для использования
        в шаблонах.
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Parameter'
            type: array
      summary: Возвращает все параметры для использования в шаблонах.
      tags:
      - parameter
  /sample:
    get:
      description: return sample data as json.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Sample'
      summary: return sample data from server
swagger: "2.0"
