basePath: /api
definitions:
  request.CreateCollectionRequest:
    type: object
  request.LoginRequest:
    properties:
      isRemember:
        type: boolean
      login:
        type: string
      password:
        type: string
    required:
    - isRemember
    - login
    - password
    type: object
  request.UpdateCollectionRequest:
    properties:
      id:
        type: integer
    type: object
  response.CollectionListResponse:
    type: object
  response.GetCollectionResponse:
    type: object
  response.LoginInfo:
    properties:
      token:
        type: string
      username:
        type: string
    required:
    - token
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: CMS с сервером на языке программирования GO
  title: keeper cms server
  version: "0.1"
paths:
  /auth/change-password:
    post:
      description: Меняет пароль по запросу пользователя
      parameters:
      - description: Параметры смены пароля
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginInfo'
      summary: Меняет пароль для пользователя
      tags:
      - auth
  /auth/login:
    post:
      description: Проводит авторизацию на сервере и возвращает информацию о пользователе.
      parameters:
      - description: Параметры аунтификации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginInfo'
      summary: Авторизирует пользователя.
      tags:
      - auth
  /collection/:
    get:
      description: Возвращает список всех коллекций на сервере.
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CollectionListResponse'
      summary: Возвращает список всех коллекций на сервере
      tags:
      - collection
    patch:
      description: Редактирует информацию о коллекции на сервере.
      parameters:
      - description: Параметры создания коллекции
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateCollectionRequest'
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
      summary: Редактирует коллекцию.
      tags:
      - collection
    post:
      description: Создаёт новую коллекцию на сервере.
      parameters:
      - description: Параметры создания коллекции
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateCollectionRequest'
      produces:
      - aplication/json
      responses:
        "201":
          description: Created
      summary: Создаёт коллекцию на сервере.
      tags:
      - collection
  /collection/{id}:
    get:
      description: Возвращает коллекцию на сервере, по id.
      parameters:
      - description: Идентификатор коллекции
        in: path
        name: id
        required: true
        type: integer
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetCollectionResponse'
      summary: Возвращает коллекцию на сервере.
      tags:
      - collection
swagger: "2.0"
