basePath: /api
definitions:
  request.CreateParameterRequest:
    properties:
      isDefault:
        description: Параметр является стандартным и доступен для всех шаблонов
        type: boolean
      name:
        description: Имя параметра
        type: string
      parameterType:
        description: Тип параметра
        type: string
    required:
    - isDefault
    - name
    - parameterType
    type: object
  request.GetParameterValuesRequest:
    properties:
      path:
        description: Путь для которого запрашиваются значения параметров
        type: string
    type: object
  request.LoginRequest:
    properties:
      isRemember:
        description: Необходимо ли запоминать пользователя
        type: boolean
      login:
        description: Логин пользователя
        type: string
      password:
        description: Пароль пользователя
        type: string
    required:
    - isRemember
    - login
    - password
    type: object
  response.LoginInfo:
    properties:
      token:
        type: string
      username:
        type: string
    required:
    - token
    - username
    type: object
  response.Parameter:
    properties:
      defaultValue:
        type: string
      id:
        type: integer
      isDefault:
        type: boolean
      isSystem:
        type: boolean
      name:
        type: string
      parameterType:
        type: string
    required:
    - defaultValue
    - id
    - isDefault
    - isSystem
    - name
    - parameterType
    type: object
host: localhost:8080
info:
  contact: {}
  description: CMS с сервером на языке программирования GO
  title: keeper cms server
  version: "0.1"
paths:
  /auth/change-password:
    post:
      description: Меняет пароль по запросу пользователя
      parameters:
      - description: Параметры смены пароля
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginInfo'
      summary: Меняет пароль для пользователя
      tags:
      - auth
  /auth/login:
    post:
      description: Проводит авторизацию на сервере и возвращает информацию о пользователе.
      parameters:
      - description: Параметры аунтификации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginInfo'
      summary: Авторизирует пользователя.
      tags:
      - auth
  /parameter:
    get:
      description: Возвращает массив параметров, предназначеных для использования
        в шаблонах.
      produces:
      - aplication/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Parameter'
            type: array
      summary: Возвращает все параметры для использования в шаблонах.
      tags:
      - parameter
  /parameter/new:
    post:
      description: Создаёт параметр.
      parameters:
      - description: Свойства создаваемого шаблона
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateParameterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Создаёт параметр для редактирования в шаблоне.
      tags:
      - parameter
  /parameter/values:
    post:
      description: Возвращает спиоск параметров для указанного шаблона, если шаблон
        не указан, то возвращает все параметры
      parameters:
      - description: Параметры запроса на получения значений параметров
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.GetParameterValuesRequest'
      produces:
      - application/json
      responses: {}
      summary: Возвращает список параметров для указанного шаблона
      tags:
      - parameter
swagger: "2.0"
